<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerShDzJxi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerShDzJxi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerShDzJxi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerShDzJxi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerShDzJxi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ShDzJxi',
    'container.build_id' => '5e47476f',
    'container.build_time' => 1554309575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerShDzJxi');
