<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAnJG2Sx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAnJG2Sx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAnJG2Sx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAnJG2Sx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAnJG2Sx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AnJG2Sx',
    'container.build_id' => 'e5a2c68a',
    'container.build_time' => 1554306027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAnJG2Sx');
