<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdaaiVU\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdaaiVU/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdaaiVU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdaaiVU\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXdaaiVU\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XdaaiVU',
    'container.build_id' => '41cbb263',
    'container.build_time' => 1553970307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdaaiVU');
